### PR TITLE
fix(synthetics): Adjust timeframes loop to include child objects

### LINKED ISSUE #100: Advanced Scheduling for Datadog Synthetics Non-Functional
### Describe the Bug

Currently unable to set advanced Scheduling options for Datadog Synthetics. While I can easily set multiple Assertions on a single Synthetic Test, I am not able to set multiple Timeframes when attempting to create an advanced schedule for Synthetics.

### Expected Behavior

When passing multiple timeframes into the Synthetics module, multiple timeframes are expected to be set for the Synthetic Test.

### Steps to Reproduce

When passed into the Synthetics module, the below will set one Timeframe for the Synthetic Test.
```
  options:
    scheduling:
      timeframes:
        day: 1
        from: "07:00"
        to: "16:00"
      timezone: "America/New_York"
```

If you pass in multiple tiemframes, even though it is a valid YAML, the module errors out.
```
  options:
    scheduling:
      timeframes:
      - day: 1
        from: "07:00"
        to: "16:00"
      - day: 2
        from: "07:00"
        to: "16:00"
      timezone: "America/New_York"
```

### Screenshots

> ╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 411, in resource "datadog_synthetics_test" "default":
│  411:               day  = timeframes.value.day
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 412, in resource "datadog_synthetics_test" "default":
│  412:               from = timeframes.value.from
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵
╷
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/datadog_synthetics/modules/synthetics/main.tf line 413, in resource "datadog_synthetics_test" "default":
│  413:               to   = timeframes.value.to
│     ├────────────────
│     │ timeframes.value is tuple with 2 elements
│ 
│ This value does not have any attributes.
╵

### Environment

_No response_

### Additional Context

There also do not appear to be any examples of this functionality in the documentation or repository.

### PR DESCRIPTION
**Pull request by elx-bob**
## what

- Change loop to use child objects instead of timeframes object.
- Update Datadog provider requirements for synthetics
- Fix broken test

## why

- Synthetics `options.scheduling.timeframes` was incorrectly treated as an object, and is now correctly treated as a list of objects, as specified in the [API documentation](https://docs.datadoghq.com/api/latest/synthetics/#create-an-api-test)
- Improved API validation at the server level uncovered a bug in the Datadog provider for synthetic tests, which was fixed in provider v3.43.1
- The test requirement that the monitor had no tags was overly strict, requiring a `nil` output rather than an empty one, causing properly working code to be marked as failing

## references

- Closes #100 
- Needed to fix https://github.com/DataDog/terraform-provider-datadog/issues/2531

### CODE REVIEW

**Comment by GabisCampana** [comment]
@Nuru

**Review by Nuru — DISMISSED** [review]

**Comment by Nuru** [comment]
@elx-bob Thank you for this PR. 

At the moment, the automated tests are failing. The test failures do not appear to be related to this PR, but still, we do not like to accept/merge PRs when the tests are failing. I am looking into it; no further action is required on your part at this time.

**Review by Nuru — APPROVED** [review]

**Pull request merged**
