### PR TITLE
rm unused provider

### PR DESCRIPTION
**Pull request by kevcube**
## what
* aws provider is not being used

## why
* adds an extra entry into my lockfile

### CODE REVIEW

**Review by Gowiem — DISMISSED** [review]

**Comment by kevcube** [comment]
@Gowiem that test failure is a weird one. any ideas?

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@kevcube looks like it was a fluke. Thanks to @joe-niland for running again!

**Comment by joe-niland** [comment]
@Gowiem yes I think a genuine networking issue or short outage

**Pull request merged**
