### PR TITLE
monitor: add new provider features

### PR DESCRIPTION
**Pull request by kevcube**
## what
- add new provider features to datadog monitors

## why
- we needed to use some of these, so while reviewing the datadog_monitor documentation I decided to make all of them available.

## references
* https://registry.terraform.io/providers/DataDog/datadog/3.21.0/docs/resources/monitor

### CODE REVIEW

**Comment by drewagentsync** [comment]
Could we get a code owner to review and comment on these changes? I could really use of a few of these new features. 🙏

**Comment by joe-niland** [comment]
Looks good @kevcube could you please pull in master and probably also run the following to be sure:

```
make init
make github/init
make readme
```

**Comment by Nuru** [comment]
Superseded and closed by #87

**Pull request closed without merging**
